### ISSUE TITLE
Stage PRs in their own schemas

### ISSUE THREAD

**Issue by matsonj** [C00ldudeNoonan/simple-dbt-runner#11]
This is pretty clever from datafold’s implementation ->

On PR:
```
- name: Find Current Pull Request
  uses: jwalton/gh-find-current-pr@v1.3.0
  id: findPR
…
SNOWFLAKE_SCHEMA: "${{ format('{0}_{1}', 'PR_NUM', steps.findPr.outputs.pr) }}"
```

Then on PR closed:
```
pull_request:
   types:
     - closed

[...]

     - name: drop PR schemas


       run: dbt run-operation drop_pr_staging_schemas --args
       "{'PR_number'":" '${PR_NUM}' }" --profiles-dir ./
```
